### ISSUE TITLE
Research on Topic modelling techniques

### ISSUE THREAD

**Issue by farukcankaya** [TUM-IDP-WS-20/doc#10]
Parent: #1 
---

- [x] Find all topic modelling techniques
- [x] Compare and document powerful features of each technique
- [x] SVD
- [x] LSA
- [x] LDA
- [x] ...

**Comment by MelikeSila** [comment]
General perspective regarding to the topic modeling techniques collected under a document https://docs.google.com/document/d/1988d2nKY4v-df_HfWaNxbSZhQVtOZLcLbyrGU9bdft8/edit?usp=sharing
