### ISSUE TITLE
Initial research on similarity measures and recommendation algorithms

### ISSUE THREAD

**Issue by MelikeSila** [TUM-IDP-WS-20/doc#11]
Parent: #1 
---
#TODO fill the sub-tasks

**Comment by farukcankaya** [comment]
- Cosine Similarity
- Pearson Similarity
- Jaccard similarity
- Euclidean distance
- Manhattan distance
- Minkowski distance

Documentation will be here: https://tum-idp-ws-20.github.io/doc/similarity-measurements
