### ISSUE TITLE
Think about finding a performance measurement for the software. i.e. how to calculate accuracy

### ISSUE THREAD

**Issue by MelikeSila** [TUM-IDP-WS-20/doc#14]
Parent: #1 
---

#TODO fill the sub-tasks

**Comment by farukcankaya** [comment]
https://www.quora.com/?pa_story=NjE5MjMwNTQ3OTM4MTM1MTU4fDIxMTEwNjIzNDM0MTUzN3ww

**Comment by farukcankaya** [comment]
There are some methods to compare the results of topic modeling techniques i.e. 'LDA Model Performance Scores' as mentioned [here](https://www.machinelearningplus.com/nlp/topic-modeling-python-sklearn-examples/#13compareldamodelperformancescores). However, evaluating the result of the system highly depends on the knowledge about the domain. Therefore, we need to work closely with a domain expert to evaluate the recommendation engine.
