### ISSUE TITLE
Add rating bar to the TUM-IDP-WS-20 / simple-recommender

### ISSUE THREAD

**Issue by MelikeSila** [TUM-IDP-WS-20/doc#27]
Add a rating bar to the simple-recommender website to take feedback from users
- [x] Create database connection
- [x] Add a rating bar
- [x] Keep the following data to analyze the result and improve the model
> - User Input
> - Currently used method ( e.g in the order lemmatization, remove stop words, LDA, etc.)
> - User rating taken from rating bar
> - Output

**Comment by farukcankaya** [comment]
Implemented in the following:
1. <a href="https://github.com/TUM-IDP-WS-20/simple-recommender/tree/fix/formatting">fix/formatting</a>
2. <a href="https://github.com/TUM-IDP-WS-20/simple-recommender/tree/feature/add_rating_star">feature/add_rating_star</a>
3. <a href="https://github.com/TUM-IDP-WS-20/simple-recommender/tree/feature/multiple_models">feature/multiple_models</a>
